# Generated by Django 4.1.5 on 2024-02-03 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role_master',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('bint_mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userdetails.country')),
                ('fk_role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userdetails.rolemaster')),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
